tree-sitter/haskell-tree-sitter

src/Text/Parser/TreeSitter/Node.hs
src/bridge.c

Bridge to the byte offset functions. Also, whatever all those other changes are which apparently haven’t landed on master?

Bridge byte offsets

---

.travis.yml

No tests or docs yet, but would be nice to at least have a check that haskell-tree-sitter compiles.

Introduce basic stack travis ci build

---

.gitignore

Adding a few things to the .gitignore.

Ignore cabal build & new-build artifacts.

---

.gitmodules
cabal.project
languages/go/Setup.hs
languages/go/TreeSitter/Go.hs
languages/go/cabal.project
languages/go/go.cabal
languages/json/Setup.hs
languages/json/TreeSitter/JSON.hs
languages/json/cabal.project
languages/json/json.cabal
languages/python/Setup.hs
languages/python/TreeSitter/Python.hs
languages/python/python.cabal
languages/ruby/TreeSitter/Ruby.hs
languages/ruby/ruby.cabal
languages/typescript/TreeSitter/TypeScript.hs
languages/typescript/typescript.cabal

This PR adds packages for the various supported parsers.

Language packages

---

.gitmodules
languages/php/TreeSitter/PHP.hs
languages/php/stack.yaml
languages/php/tree-sitter-php.cabal
stack.yaml

Adds bindings to https://github.com/tree-sitter/tree-sitter-php.

Add tree-sitter-php haskell bindings

---

script/update-languages

This patch performs the tree-sitter 💃 and bumps tree-sitter languages to use tree-sitter version 0.11.
Also added for convenience is `script/update-languages`, which is a simple script for automating this process for the future.

Update tree sitter 0.11

---

haskell-tree-sitter.cabal

Straightforward relaxation of the TH dependency’s upper bound.

Bump the template-haskell bounds to support GHC 8.4 Stackages.

---

.vscode/settings.json
README.md
haskell-tree-sitter.cabal
includes/tree_sitter_ptr.h
languages/haskell/examples/Demo.hs
languages/haskell/examples/DemoPtr.hs
languages/haskell/stack.yaml
languages/haskell/tree-sitter-haskell.cabal
src/TreeSitter/Ptr.hsc
src/bridge_ptr.c
stack.yaml

…ased FFI
updated to stack lts-12.17

added Demo.hs for existing FFI + DemoPtr.hs for alternate FFI + update to stack lts-12.17

---

haskell-tree-sitter.cabal
languages/go/tree-sitter-go.cabal
languages/haskell/tree-sitter-haskell.cabal
languages/java/tree-sitter-java.cabal
languages/json/tree-sitter-json.cabal
languages/php/tree-sitter-php.cabal
languages/python/tree-sitter-python.cabal
languages/ruby/tree-sitter-ruby.cabal
languages/typescript/tree-sitter-typescript.cabal

This should get us closer to a releasable package, which should
unblock us on a number of issues.

Add version bounds to all packages.

---

languages/go/tree-sitter-go.cabal
languages/haskell/tree-sitter-haskell.cabal
languages/java/tree-sitter-java.cabal
languages/json/tree-sitter-json.cabal
languages/php/tree-sitter-php.cabal
languages/python/tree-sitter-python.cabal
languages/ruby/tree-sitter-ruby.cabal
languages/tsx/tree-sitter-tsx.cabal
languages/typescript/tree-sitter-typescript.cabal

With this, master reflects what we have on Hackage.

Packaging fixes for language submodules.

---

languages/python/TreeSitter/Python/AST.hs
src/CodeGen/GenerateSyntax.hs
src/TreeSitter/Importing.hs
src/TreeSitter/Language.hs
src/TreeSitter/Parser.hs

This PR merges `master` & #147 into #144.

Merge safe nodeSymbol handling into #144

---

tree-sitter/src/CodeGen/GenerateSyntax.hs

The toConLeaf and toLeafVarBangTypes functions can be consolidated
into one, since the latter is not used anywhere. While we're at it, we
can give it a more descriptive name.

Refactor: rename and simplify toConLeaf.

---

tree-sitter/src/CodeGen/Deserialize.hs
tree-sitter/src/CodeGen/GenerateSyntax.hs

rename isName to datatypeNameStatus

---

tree-sitter-python/test/Main.hs
tree-sitter-python/tree-sitter-python.cabal
tree-sitter/src/CodeGen/GenerateSyntax.hs
tree-sitter/src/TreeSitter/Unmarshal.hs

It hit me that we don't have any tests for unmarshaling, which is one
of the reasons why I introduced a bug in #163 without my noticing.
This adds a tiny test suite that we'll flesh out as we go.

Add unmarshaling tests and fix bug introduced in #163.

---

tree-sitter-python/TreeSitter/Python/AST.hs
tree-sitter-python/test/Main.hs
tree-sitter/src/TreeSitter/Deserialize.hs
tree-sitter/src/TreeSitter/GenerateSyntax.hs
tree-sitter/test-codegen/test-codegen.hs
tree-sitter/tree-sitter.cabal

move CodeGen.* files into TreeSitter.*

---

tree-sitter-python/test/Main.hs
tree-sitter/src/TreeSitter/Cursor.hs
tree-sitter/src/TreeSitter/Deserialize.hs
tree-sitter/src/TreeSitter/GenerateSyntax.hs
tree-sitter/src/TreeSitter/Node.hs
tree-sitter/src/TreeSitter/Unmarshal.hs
tree-sitter/src/bridge.c
tree-sitter/test/Spec.hs

Fixes #162 
This is a change that will enforce compile-time code-generation and downstream AST building that is more representative of the structure of the code. 
This code touches the FFI, please apply extra care and caution while reviewing. 😬

Children fields

---

tree-sitter-python/test/Main.hs
tree-sitter-python/tree-sitter-python.cabal

Bump python grammar

---

tree-sitter-python/test/Main.hs
tree-sitter/src/TreeSitter/Unmarshal.hs

Unmarshal empty modules

---

.stylish-haskell.yaml
tree-sitter-go/TreeSitter/Go/AST.hs
tree-sitter-java/TreeSitter/Java/AST.hs
tree-sitter-json/TreeSitter/JSON/AST.hs
tree-sitter-php/TreeSitter/PHP/AST.hs
tree-sitter-python/TreeSitter/Python/AST.hs
tree-sitter-ruby/TreeSitter/Ruby/AST.hs
tree-sitter-tsx/TreeSitter/TSX/AST.hs
tree-sitter-typescript/TreeSitter/TypeScript/AST.hs
tree-sitter/src/TreeSitter/GenerateSyntax.hs
tree-sitter/src/TreeSitter/Unmarshal.hs

This PR defines `HasField "ann"` instances for (named) sums using `HasField "ann"` instances for their members.
Fixes #208.

HasField instances for sums

---

tree-sitter-go/tree-sitter-go.cabal
tree-sitter/ChangeLog.md
tree-sitter/src/TreeSitter/Cursor.hs
tree-sitter/src/TreeSitter/Node.hs
tree-sitter/tree-sitter.cabal

Bump tree-sitter & tree-sitter-go versions

---

tree-sitter-json/tree-sitter-json.cabal

I published with this local change, but forgot to commit. Follow on from https://github.com/tree-sitter/haskell-tree-sitter/pull/267

Include *.tx in json package

---

.gitmodules
tree-sitter-rust/ChangeLog.md
tree-sitter-rust/Setup.hs
tree-sitter-rust/TreeSitter/Rust.hs
tree-sitter-rust/tree-sitter-rust.cabal

An attempt to add [tree-sitter/tree-sitter-rust](https://github.com/tree-sitter/tree-sitter-rust) support.

Add tree-sitter-rust

---

tree-sitter-rust/TreeSitter/Rust.hs
tree-sitter-rust/tree-sitter-rust.cabal

This PR aims to solve issues #277 and #278

bug fixes for tree-sitter-rust

---

tree-sitter-php/ChangeLog.md
tree-sitter-php/tree-sitter-php.cabal

The submodule was bumped in https://github.com/tree-sitter/haskell-tree-sitter/pull/280.

Bump tree-sitter-php to 0.5.0.0.
