tree-sitter/haskell-tree-sitter

- src/Text/Parser/TreeSitter/Document.hs
- src/Text/Parser/TreeSitter/Node.hs
`unsafe` means that we know that these will never call back into Haskell, and thus the runtime can skip a bunch of checks that it would otherwise need to use.
This is saving us about half a second in the case I’m testing.
> Unsafe FFI calls

- src/bridge.c
This is intended to ease some experimentation where we don’t need the production name, just the symbol (which is available as of #7).
> Allow null document pointers

- src/Text/Parser/TreeSitter/Language.hs
This PR defines a `Symbol` typeclass, enabling consumers of symbol datatypes to query whether a given symbol is anonymous &c.
> Classify symbols

- src/Text/Parser/TreeSitter/Language.hs
A `Bounded` instance allows us to bounds-check uses of `toEnum` to e.g. deal with `ERROR` productions. An `Ix` instance allows us to perform that bounds-check using the `inRange` method.
> Derive Bounded & Ix instances for grammar datatypes.

- src/Text/Parser/TreeSitter/Language.hs
This PR adds an error constructor to each templated grammar datatype.
> Add constructors for error productions

- src/Text/Parser/TreeSitter/Language.hs
This PR places the `ParseError` constructor at the end, and resumes deriving the `Enum` instance, fixing the mismatch between unsigned `TSSymbol` values and the `ParseError` constructor, at the cost of requiring a bounds check on `nodeSymbol` before using `toEnum`.
> Parse errors as maximal symbol

- src/Text/Parser/TreeSitter/Language.hs
With `alias` rules we produce symbols of the same name multiple times. This prevents duplicate symbol names from occurring in the named symbols returned from haskell tree sitter for a given tree-sitter grammar.
Duplicate symbols' names are updated with a `'` to maintain uniqueness.
🎩  @robrix for 🍐  and deep dive.
> Name constructors uniquely

- haskell-tree-sitter.cabal
- src/Text/Parser/TreeSitter.hs
- src/TreeSitter/Document.hs
- src/TreeSitter/Language.hs
- src/TreeSitter/Node.hs
This PR removes the `Text.Parser` prefix from the modules.
> Simplify the module hierarchy.

- haskell-tree-sitter.cabal
- src/Text/Parser/TreeSitter/Language.hs
This lets languages easily specify various files that they might be dependent on so that, for example, `mkSymbolDatatype` will re-run when something in the tree-sitter grammar has changed.
> Allow adding of relative, dependent files for TH

- src/TreeSitter/Language.hs
This PR gives `Symbol` a bunch of superclasses that we need basically any time we’re using them.
> Symbol superclasses

- languages/go/stack.yaml
- languages/json/stack.yaml
- languages/python/stack.yaml
- languages/ruby/stack.yaml
- languages/typescript/stack.yaml
- stack.yaml
It seems stack needs these in order to prevent rebuilding when running `stack build` multiple times.
> Add stack files to prevent haskell-tree-sitter from rebuilding

- haskell-tree-sitter.cabal
- src/TreeSitter/Node.hs
- src/bridge.c
- stack.yaml
- test/Spec.hs
This PR 🔥s the dependency on `c-storable-deriving`, opting to implement `poke` manually instead for the various node types.
Fixes #39.
> Remove c-storable-deriving, bump all the things

- src/TreeSitter/Parser.hs
- src/bridge.c
Hooks into `ts_parser_enabled` and `ts_parser_set_enabled`. Bumps tree-sitter.
> Add support for cancelling an in-flight parse.

- .gitmodules
- haskell-tree-sitter.cabal
- languages/go/tree-sitter-go.cabal
- languages/haskell/Setup.hs
- languages/haskell/TreeSitter/Haskell.hs
- languages/haskell/cabal.project
- languages/haskell/stack.yaml
- languages/haskell/tree-sitter-haskell.cabal
- languages/json/tree-sitter-json.cabal
- languages/php/tree-sitter-php.cabal
- languages/python/tree-sitter-python.cabal
- languages/ruby/tree-sitter-ruby.cabal
- languages/typescript/tree-sitter-typescript.cabal
- src/TreeSitter/Language.hs
- src/TreeSitter/Node.hs
- src/TreeSitter/Parser.hs
- src/TreeSitter/Tree.hs
- stack.yaml
Also updates the author field in all cabal files to add @aymannadeem and @patrickt 😄 
@robrix, I've also removed the Prelude imports statements from the `TreeSitter` modules.
> Add tree-sitter-haskell bindings

- src/TreeSitter/Node.hs
`Struct` is already strict in its result value; this PR additionally makes it strict in the pointer value.
> Operate strictly in the pointers

- src/TreeSitter/Node.hs
Given certain pathological input, such as an array literal with 150000
elements, the ts_node_copy_child_nodes function can take an extremely
long time. While we may be able to make this more performant,
fundamentally this is a situation where a client should use a timeout.
Unfortunately, because this function is called via the FFI, `timeout`
will not properly interrupt a call to ts_node_copy_child_nodes, as
per the GHC manual:
> Normally when the target of a throwTo is involved in a foreign call,
> the exception is not raised until the call returns, and in the
> meantime the caller is blocked. This can result in unresponsiveness,
> which is particularly undesirable in the case of user
> interrupt (e.g. Control-C).
We have two options here: we can either change
ts_node_copy_child_nodes to …
> Mark ts_node_copy_child_nodes as interruptible from Haskell.

- src/TreeSitter/Node.hs
- src/bridge.c
This loop was slow for two reasons: firstly, we were using
`ts_node_child` to access the children of a given node, which entails
a logarithmic slowdown as the number of children exists, since these
nodes are stored in a balanced binary tree. Switching to the
`TSCursor` API means that we can traverse the node's children in
constant per-step time.
This also retools ts_node_elaborate to operate solely on pointer
values rather than incur the effort of allocating and returning a
struct value and then copying it into a pointer location. Some [tests](https://godbolt.org/z/VScV5k)
with the godbolt compiler explorer indicate that this avoids 
significant overhead, about a dozen `mov` instructions per iteration.
On an array with 175000 elements, this reduces processing time from 12
minutes to less …
> Fix logarithmic slowdown in ts_node_copy_child_nodes (#66)

- src/TreeSitter/Node.hs
Since the `Storable` instance for `Node` is implemented in terms of
the `evalStruct` function, it behooves us to avoid partial application
and function composition in its definition, as partially-applied
functions are slower than fully-applied ones.
When compiling with -O0, this produces _drastically_ faster parses on
large files: on a 5MB Go file parses went from 17sec to 7sec. The
improvement is less noticeable on when compiling with -O2, but is
still present (~0.5sec).
> Inline and avoid partial application in evalStruct.

- Setup.hs
- haskell-tree-sitter.cabal
- includes/tree_sitter_ptr.h
- languages/go/tree-sitter-go.cabal
- languages/haskell/tree-sitter-haskell.cabal
- languages/java/tree-sitter-java.cabal
- languages/json/tree-sitter-json.cabal
- languages/php/tree-sitter-php.cabal
- languages/python/tree-sitter-python.cabal
- languages/ruby/tree-sitter-ruby.cabal
- languages/typescript/tree-sitter-typescript.cabal
- src/TreeSitter/Language.hs
- src/TreeSitter/Parser.hs
- src/TreeSitter/Ptr.hsc
- src/TreeSitter/Tree.hs
- src/bridge.c
- src/bridge_ptr.c
- test/Spec.hs
Now that https://github.com/tree-sitter/tree-sitter/pull/301 is done, we have a simpler way to impose timeouts on parsing.
This PR updates the Tree-sitter submodule and exposes the new timeout functions. I've also removed the `set_enabled` functions, because those underlying Tree-sitter functions were changed in https://github.com/tree-sitter/tree-sitter/pull/306.
> Update Tree-sitter, expose new timeout API

- README.md
- languages/haskell/tree-sitter-haskell.cabal
These are taking up unnecessary time on the builders.
To build with these on, do `stack build --flag tree-sitter-haskell:build-examples`
> Hide tree-sitter-haskell examples behind a cabal flag.

- haskell-tree-sitter.cabal
- src/TreeSitter/Cursor.hs
- src/TreeSitter/Importing.hs
- src/TreeSitter/Node.hs
- src/bridge.c
- test/Spec.hs
🎩 @aymannadeem
cc @maxbrunsfeld
> Import datatypes via the Cursor API

- .travis.yml
- languages/python/TreeSitter/Python.hs
- languages/python/tree-sitter-python.cabal
We weren’t building all the targets, which means that `tree-sitter-python` compilation has been broken on master for some time. This fixes it.
> Build all language subprojects in CI.

- src/TreeSitter/Parser.hs
Fixes #2, albeit in the boring-est way possible (just returning a `Bool`, offering no support to actually indicate which versions we’re dealing with).
> Check for incompatible parser versions

- languages/go/stack.yaml
- languages/haskell/stack.yaml
- languages/java/stack.yaml
- languages/json/stack.yaml
- languages/php/stack.yaml
- languages/python/stack.yaml
- languages/ruby/stack.yaml
- languages/typescript/stack.yaml
- stack.yaml
We're deprecating `stack` as the environment of choice for hacking on
the Semantic ecosystem, but I don't want to blow up @aymannadeem's
setup yet, so this doesn't yet remove the main stack.yaml. It does,
however, remove all the other nested stack files, and works with #121.
Fixes #109.
> Remove per-language .stack.yaml files and bump LTS version.

- .travis.yml
- src/CodeGen/GenerateSyntax.hs
Targeting newer GHCs makes our lives easier (and is fine because the
8.6-only `semantic` is the only app depending on this). The fewer
carbon emissions, the better, IMO.
Also fixes a stray import that 8.2 was complaining about.
> Only test on GHC 8.6.

- languages/go/tree-sitter-go.cabal
I’m not sure if this is necessary, but it might be.
> Ensure we get the parser header file.

- tree-sitter/src/CodeGen/GenerateSyntax.hs
- tree-sitter/test-codegen/test-codegen.hs
Since both "map" and "operator" are pretty overloaded words in
Haskell, I figured we could pick a more specific name as to this
function. I also pulled out its helper into a lambda-case, since it
wasn't used anywhere else and didn't entail big churn in the diff.
> Refactor: give mapOperator a more descriptive name

- tree-sitter/src/CodeGen/Deserialize.hs
- tree-sitter/src/CodeGen/GenerateSyntax.hs
Fixes #106
Removing the `Mk` prefixes I included for the datatypes in our Deserialize module. This was originally intended to disambiguate the datatypes but is no longer relevant.
> Remove `Mk` prefixes on datatypes

- tree-sitter/src/CodeGen/Deserialize.hs
- tree-sitter/src/CodeGen/GenerateSyntax.hs
There are a lot of functions that begin with `to`, and I'm having
trouble keeping them straight. This patch helps address that by
renaming `toType` to `fieldTypesToNestedEither`, which is much more
specific about its inputs and outputs.
I also removed an error case by switching `MkField` to contain a
`NonEmpty Type` instead of a `[Type]`, and simplified the call to
`fieldTypesToNestedEither` in `toVarBangType`.
> Refactor: rename and simplify toType.

- tree-sitter/src/CodeGen/GenerateSyntax.hs
As per #164 and #167, this saves us lines of code and generally
improves nomenclature.
> Refactor: rename toConProduct

- tree-sitter/src/CodeGen/GenerateSyntax.hs
As per #163 and #164, we can lose lines and gain clarity by
consolidating helper functions, renaming the toplevel function, and
using the TH.Lib syntax for building ASTs.
> Refactor: rename toSumCon

- tree-sitter/src/TreeSitter/Unmarshal.hs
Fixes #102
Repeated fields were represented in the tree as multiple nodes with the same field name. We were only representing a single node for each field name, keeping only the last one encountered in the tree. This change fixes that.
> Build ASTs without dropping fields

- tree-sitter/src/TreeSitter/GenerateSyntax.hs
- tree-sitter/src/TreeSitter/Language.hs
We were treating these as tho referentially transparent, but it appears that this wasn’t the case: as @aymannadeem & @patrickt diagnosed, sometimes `ts_language_symbol_type` would return 0 when it should have returned 1, specifically when invoked via `cabal v2-haddock` (!).
At the same time, we were getting the correct results from `ts_language_symbol_name`, making me think that the symbol metadata & symbol names arrays might have been initialized at different times… or something. (@maxbrunsfeld, does that sound plausible at all? Could the symbol metadata have been zero-initialized, or get initialized with its correct values on library load or something?)
Either way, this PR fixes this issue and should make builds involving TH (e.g. `tree_sitter_python`) more reliable.
> Sequence TreeSitter.Language functionality in IO

- tree-sitter/src/TreeSitter/Cursor.hs
- tree-sitter/src/TreeSitter/Language.hs
- tree-sitter/src/TreeSitter/Parser.hs
- tree-sitter/src/TreeSitter/Tree.hs
We didn't export these constructors anyway, so there is no effect on
compatibility here.
> Remove pointer-only constructors (#146).

- script/build_and_upload
As a pairing session with @aymannadeem revealed on Friday, the build-test-upload-retest cycle of Hackage uploads can be really tedious and entails a lot of copying and pasting. This bash script takes care of a lot of that tedium.
> Add script to automate parts of build/upload process.

- tree-sitter-php/tree-sitter-php.cabal
@KevOrr helped us out with getting some of PHP's more obscure
precedences (like left-associative ternary operators) correct. Let's
pull these changes in so that we get better results in Semantic.
> Pull in precedence bugfixes from tree-sitter-php.

- tree-sitter/tree-sitter.cabal
As @robrix pointed out, this is not good practice, and we don't even
use `hedgehog` in the library itself, so :fire:.
> Remove hedgehog dependency from tree-sitter:lib.

- tree-sitter-python/test/Main.hs
- tree-sitter/src/TreeSitter/Unmarshal.hs
- tree-sitter/test-codegen/test-codegen.hs
`insertWith`, unlike `unionWith`, applies the passed function to the operands in the opposite order to what we expected. This means that we were inserting new nodes at the head of the list every time, and thus reversing the lists of nodes, such that unmarshalling would produce reversed lists.
> Insert nodes into fields in the correct order

- tree-sitter/test/Spec.hs
- tree-sitter/tree-sitter.cabal
The `tree-sitter:test` component won’t link for me locally, and I don’t know why. It also seemed a little unnecessary to have all these different test tools in flight, so this PR simplifies things by just using `hedgehog`.
> Run the main unit tests using hedgehog instead of hspec

- tree-sitter-python/ChangeLog.md
- tree-sitter-python/tree-sitter-python.cabal
- tree-sitter/ChangeLog.md
- tree-sitter/tree-sitter.cabal
I took the liberty of adding changelog files because I was sick of the
Hackage candidate page chastising me for their absence.
When this lands, I will push up `tree-sitter-0.2.1.0` and
`tree-sitter-python-0.3.0.0` tags.
This will allow `semantic-python` to ingest that good good annotation info.
> Release tree-sitter-0.2.1 and tree-sitter-python-0.3.

- tree-sitter-python/tree-sitter-python.cabal
For paranoia's sake, let's use exact version bounds for releases that
depend very specifically on the output from a tree-sitter macro.
> Narrow version bounds and release tree-sitter-python-0.3.

- script/bootstrap
- script/build-and-upload
- script/update-languages
- tree-sitter-tsx/tree-sitter-tsx.cabal
- tree-sitter-typescript/tree-sitter-typescript.cabal
Pick up fix for state merging that was causing some parse failures. https://github.com/tree-sitter/tree-sitter-typescript/commit/2573038b6c77840618df17064800c914234207cb.
> Bump tree-sitter-typescript

- tree-sitter-python/TreeSitter/Python/AST.hs
- tree-sitter-python/test/Main.hs
- tree-sitter/src/TreeSitter/GenerateSyntax.hs
- tree-sitter/src/TreeSitter/Unmarshal.hs
Fixes #197, #209, #182 
This PR replaces the use of the `Either` type with `:+:` for anonymous sums. This has a few effects:
1. **The shape of our data changes.** A given anonymous sum represented with `Either` looks like this: `Either (X a) (Y a)`, with the type parameter `a` being applied "inside". By contrast, the use of `:+:` would give us `(X :+: Y) a`, where the constructors are summed and then applied to the type parameter. 
2. **The kind signature changes.** `Either` is `* -> * -> *`: it takes two fully-applied types and gives you a fully-applied type, whereas `:+:` is `(* -> *) -> (* -> *) -> (* -> *)`:  it takes two type constructors and gives you a type constructor. This allows @patrickt to define a `Compile` interface to be of `* -> *` instead of `*`.
3. **We can now derive …
> No more eithers

- tree-sitter-python/test/Main.hs
- tree-sitter/src/TreeSitter/GenerateSyntax.hs
- tree-sitter/src/TreeSitter/Unmarshal.hs
- tree-sitter/src/TreeSitter/Unmarshal/Examples.hs
This changes `Unmarshal` to operate on type constructors of kind * -> * instead of types of kind *, allowing us a great deal more latitude in separating out the various roles types play in our ASTs. This was made possible by @aymannadeem’s work in #214, and results in a substantial simplification to the implementation, which just goes to show what you can accomplish with parametricity.
> Unmarshal at * -> *

- tree-sitter/src/TreeSitter/Unmarshal.hs
Forgot this one: we need to unmarshal `Loc` from `semantic-source` in addition to `Range` and `Span`.
> Define an UnmarshalAnn instance for Source.Loc

- tree-sitter-python/TreeSitter/Python/AST.hs
- tree-sitter-python/test/Main.hs
- tree-sitter/src/TreeSitter/GenerateSyntax.hs
- tree-sitter/src/TreeSitter/Symbol.hs
- tree-sitter/src/TreeSitter/Token.hs
- tree-sitter/src/TreeSitter/Unmarshal.hs
- tree-sitter/src/TreeSitter/Unmarshal/Examples.hs
- tree-sitter/tree-sitter.cabal
This PR replaces the `NewtypeD` we generated for anonymous leaf types with a type synonym for a common `Token` type, indexed by both the symbol name and value for the grammar rule it corresponds to.
This allows us to avoid deriving a _lot_ of instances, and thus improve compile times for the AST modules by a decent margin.
Fixes #139.
> Common representation for anonymous (token) AST nodes

- script/build-and-upload
- tree-sitter-go/tree-sitter-go.cabal
- tree-sitter-haskell/tree-sitter-haskell.cabal
- tree-sitter-java/ChangeLog.md
- tree-sitter-java/tree-sitter-java.cabal
- tree-sitter-json/ChangeLog.md
- tree-sitter-json/tree-sitter-json.cabal
- tree-sitter-nix/tree-sitter-nix.cabal
- tree-sitter-php/tree-sitter-php.cabal
- tree-sitter-python/ChangeLog.md
- tree-sitter-python/tree-sitter-python.cabal
- tree-sitter-ruby/tree-sitter-ruby.cabal
- tree-sitter-tsx/tree-sitter-tsx.cabal
- tree-sitter-typescript/tree-sitter-typescript.cabal
- tree-sitter/ChangeLog.md
- tree-sitter/src/TreeSitter/GenerateSyntax.hs
- tree-sitter/tree-sitter.cabal
We can’t release `tree-sitter-json` on `master` as 0.2.1.0, because it requires us to have the `skipDefined` codegen stuff, which isn’t available in a published `tree-sitter`.
**To-do:**
> Reversion tree-sitter-json & correct its lower bound on tree-sitter

- docs/codegen.md
- tree-sitter-python/test/Main.hs
- tree-sitter/src/TreeSitter/GenerateSyntax.hs
- tree-sitter/src/TreeSitter/Strings.hs
- tree-sitter/src/TreeSitter/Unmarshal.hs
- tree-sitter/test-codegen/test-codegen.hs
- tree-sitter/test/Test.hs
- tree-sitter/test/TreeSitter/Example.hs
- tree-sitter/test/TreeSitter/Strings/Example.hs
- tree-sitter/tree-sitter.cabal
I noticed that python imports like `from foo import a, b, c` are not unmarshalling properly with an error `expected a node but didn't get one`. In debugging this, I've added a unit test, made the error messages a bit more informative and unique, and made a naming fix.
I'm now running into an issue in tree-sitter-python. `master` has the proper node-types.json for `import_from_statement`, but is missing a top level definition of `keyword_identifier`. If you use the following patch to manually fix `import_from_statement`, these tests pass.
``` diff
diff --git a/src/node-types.json b/src/node-types.json
index 2587a32..5825ca6 100644
--- a/src/node-types.json
+++ b/src/node-types.json
@@ -1370,8 +1370,8 @@
}
},
"children": {
-      "multiple": true,
-      "required": true,
+      "multiple": …
```
> Python AST fixes for `import_from_statement`

- cabal.project
- tree-sitter/src/TreeSitter/Unmarshal.hs
- tree-sitter/tree-sitter.cabal
Reverts tree-sitter/haskell-tree-sitter#233
This is a temporary revert until semantic is ready to upgrade to fused-effect 1.0 so that we can do a tree-sitter bump.
> Revert "Upgrade to fused-effects-1.0."

- tree-sitter-java/test/Test.hs
- tree-sitter-python/test/Test.hs
- tree-sitter-test-helpers/src/TreeSitter/Test/Helpers.hs
`cabal test` moves into the subproject's folder before running,
whereas `cabal run` doesn't. We can fix this by conditionally entering
the `tree-sitter-python` directory.
> Ensure tree-sitter-python tests can be run with `cabal run` from the top-level project folder.

- tree-sitter/src/TreeSitter/GenerateSyntax.hs
Adds span information to the message from SymbolMatching's `showFailure` method.
> Slightly improved showFailure message

- tree-sitter-go/TreeSitter/Go.hs
- tree-sitter-go/tree-sitter-go.cabal
- tree-sitter-java/TreeSitter/Java.hs
- tree-sitter-java/tree-sitter-java.cabal
- tree-sitter-json/TreeSitter/JSON.hs
- tree-sitter-json/tree-sitter-json.cabal
- tree-sitter-python/TreeSitter/Python.hs
- tree-sitter-python/tree-sitter-python.cabal
- tree-sitter-ruby/TreeSitter/Ruby.hs
- tree-sitter-ruby/tree-sitter-ruby.cabal
- tree-sitter-tsx/TreeSitter/TSX.hs
- tree-sitter-tsx/tree-sitter-tsx.cabal
- tree-sitter-typescript/TreeSitter/TypeScript.hs
- tree-sitter-typescript/tree-sitter-typescript.cabal
Includes the tree-sitter test corpus so that dependent packages can leverage these example fixtures as needed. I'll demonstrate usage over on https://github.com/github/semantic next.
> Package up the tree-sitter test corpus

- tree-sitter/ChangeLog.md
- tree-sitter/tree-sitter.cabal
`semantic-source` was required by `tree-sitter`  in the past, but for now `semantic-source` is no longer needed in `tree-sitter`.
@patrickt and I attempted to remove `tree-sitter` from the existing published `semantic-source` package, but Hackage does not support revisions that remove dependencies at this time.
So this patch formalizes the removal of `tree-sitter` and bumps the version to `0.9.0.1`.
> Remove semantic source dependency

- tree-sitter-ql/ChangeLog.md
- tree-sitter-ql/tree-sitter-ql.cabal
I've bumped the `tree-sitter-ql` parser to include named field nodes. I think these were lost by accident in previous iterations of the `tree-sitter-ql` grammar. I've also published a new version of [`tree-sitter-ql`](https://hackage.haskell.org/package/tree-sitter-ql-0.1.0.2) to hackage.
> Bump tree-sitter-ql to pull in named fields

- .gitmodules
- tree-sitter-c-sharp/ChangeLog.md
- tree-sitter-c-sharp/Setup.hs
- tree-sitter-c-sharp/TreeSitter/CSharp.hs
- tree-sitter-c-sharp/tree-sitter-c-sharp.cabal
Add's C# support here in order to get closer to C# semantic code support on GitHub.com
Not sure how to test this locally but the CI/GH Actions are passing including running the corpus tests.
Let me know if anything else needs to happen either on this repo, tree-sitter-c-sharp or elsewhere!
Fixes #185
> Add C# language support

- .github/workflows/ci.yml
- tree-sitter-c-sharp/tree-sitter-c-sharp.cabal
Ironically, the relevant `??=` glyph compiles to `#`!
Fixes #284.
> Ensure trigraphs are ignored when compiling C# parser.

- .gitmodules
- tree-sitter-ocaml/ChangeLog.md
- tree-sitter-ocaml/Setup.hs
- tree-sitter-ocaml/TreeSitter/OCaml.hs
- tree-sitter-ocaml/tree-sitter-ocaml.cabal
Initial support for https://github.com/github/semantic/issues/138
I based it on the current Rust support in both Tree-sitter and Semantic.
Requires a regenerated OCaml parser  at https://github.com/tree-sitter/tree-sitter-ocaml/pull/37
> Add OCaml support

- tree-sitter/src/TreeSitter/Symbol.hs
I added some reserved names that should be avoided as haskell identifier. I took the list from https://wiki.haskell.org/Keywords.
The space character was missing from the list of special characters.
The field names `class` and `default`, and the anonymous node `" "` currently occur in [tree-sitter-ocaml](https://github.com/tree-sitter/tree-sitter-ocaml).
Another problem that I encountered is that some supertypes (e.g. [`_sequence_expression`](https://github.com/tree-sitter/tree-sitter-ocaml/blob/ac885cabeeec4d8b5ed1dcd577533b0b549496fe/grammar.js#L965)) are too similar to other nodes (`sequence_expression`) and result in the same identifier. I don't think this can be solved by haskell-tree-sitter in a backwards compatible way, so this should probably be forbidden by tree-sitter (and …
> Add reserved names

- .github/dependabot.yml
- .github/workflows/ci.yml
- tree-sitter/ChangeLog.md
- tree-sitter/tree-sitter.cabal
This PR updates the CI setup a bit:
* The `tested-with` stanza of the cabal file is updated to reflect a canonical list of GHC versions that are being actively tested.
* This list is used to generate a CI matrix.
* Supported `base` version is set to 4.14 / GHC 8.10.7, which makes some conditionals like ` if (impl(ghc >= 8.6))` redundant.
* A dependabot config has been setup to offer PR to update the github actions used.
> Generate test matrix from tested-with GHCs

- tree-sitter-haskell/examples/Demo.hs
[tree-sitter-haskell/examples/Demo.hs](https://github.com/tree-sitter/haskell-tree-sitter/blob/master/tree-sitter-haskell/examples/Demo.hs) fails to compile with the following error:
```
• Couldn't match expected type ‘Node -> TSPoint’
with actual type ‘TSPoint’
• In the pattern: TSPoint {..}
In a pattern binding: TSPoint {..} = nodeStartPoint
In the expression:
do theType <- peekCString nodeType
let TSPoint {..} = nodeStartPoint
start = "(" ++ show pointRow ++ "," ++ show pointColumn ++ ")"
let TSPoint {..} = nodeEndPoint
end = "(" ++ show pointRow ++ "," ++ show pointColumn ++ ")"
print $ theType ++ start ++ "-" ++ end
|
82 |   let TSPoint {..} = nodeStartPoint
|       ^^^^^^^^^^^^
```
The problem is tat since 8ae40b366f9a615b58f2a171a801f6cd0fa12325 `nodeStartPoint` is not a field but …
> Fix tree-sitter-haskell example

- tree-sitter-c-sharp/tree-sitter-c-sharp.cabal
- tree-sitter-go/tree-sitter-go.cabal
- tree-sitter-haskell/examples/Demo.hs
- tree-sitter-haskell/tree-sitter-haskell.cabal
- tree-sitter-java/tree-sitter-java.cabal
- tree-sitter-json/tree-sitter-json.cabal
- tree-sitter-nix/tree-sitter-nix.cabal
- tree-sitter-ocaml/TreeSitter/OCaml.hs
- tree-sitter-ocaml/tree-sitter-ocaml.cabal
- tree-sitter-php/TreeSitter/PHP.hs
- tree-sitter-php/tree-sitter-php.cabal
- tree-sitter-python/tree-sitter-python.cabal
- tree-sitter-ruby/tree-sitter-ruby.cabal
- tree-sitter-rust/tree-sitter-rust.cabal
- tree-sitter-tsx/tree-sitter-tsx.cabal
- tree-sitter-typescript/tree-sitter-typescript.cabal
- tree-sitter/src/TreeSitter/Cursor.hs
- tree-sitter/src/TreeSitter/Parser.hs
- tree-sitter/tree-sitter.cabal
This MR changes the commit used in the `tree-sitter/vendor/tree-sitter` directory to a more recent commit.
After this, a problem popped up where compilation would fail on `ts_parser_halt_on_error`, so this foreign import was removed.
There were some broken symlinks that were causing Stack to not be able to clone the project as well, so they were removed.
> Bump tree-sitter version and deal with arising issues
